project_id = "zjbzjtljoxwreyhlrjbq"

[functions.typeform-webhook]
verify_jwt = false

[functions.import-caregivers-csv]
verify_jwt = false

[functions.formless-webhook]
verify_jwt = false

[functions.get-all-caregivers]
verify_jwt = true

[functions.invite-caregivers]
verify_jwt = true

[functions.send-message-notification]
verify_jwt = false

[functions.send-parent-message-notification]
verify_jwt = false

[functions.get-parent-conversations]
verify_jwt = false

[functions.get-parent-messages]
verify_jwt = false

[functions.send-parent-message]
verify_jwt = false

[functions.get-parent-request]
verify_jwt = false

[functions.create-caregiver-subscription]
verify_jwt = false

[functions.check-caregiver-subscription]
verify_jwt = false

[functions.mark-as-booked]
verify_jwt = true

[functions.generate-request-synopsis]
verify_jwt = true

[functions.send-match-notifications]
verify_jwt = true

[functions.get-parent-matches]
verify_jwt = false

[functions.parent-match-response]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
