project_id = "zjbzjtljoxwreyhlrjbq"

[functions.create-commission-checkout]
verify_jwt = false

[functions.stripe-commission-webhook]
verify_jwt = false

[functions.typeform-webhook]
verify_jwt = false

[functions.import-caregivers-csv]
verify_jwt = false

[functions.formless-webhook]
verify_jwt = false

[functions.get-all-caregivers]
verify_jwt = false

[functions.invite-caregivers]
verify_jwt = false

[functions.send-message-notification]
verify_jwt = false

[functions.send-parent-message-notification]
verify_jwt = false
