UPDATE public.caregivers
SET 
  pronouns = 'She/ Her',
  first_name = 'Stephanie',
  last_name = 'Strugnell',
  phone = '+447986665639',
  address = '80 Crouch House Road',
  city_town = 'Edenbridge',
  state_region_province = 'Kent',
  zip_post_code = 'TN8 5EW',
  country = 'GB',
  is_hypnobirthing_coach = true,
  speaks_english = true,
  certifications_training = 'BSc (Hons) Psychology
PG Cert in Low Intensity Cognitive Behavioural Interventions
Mindful Mamma Practitioner Training to teach Mindful Hypnobirthing and Mindful Mamma 
Diploma in Antenatal and Postnatal Education (Our Baby Club)',
  years_practicing = 'Less than one year',
  births_supported = '6-15',
  offers_birth_planning = true,
  offers_postnatal_support = true,
  offers_hypnobirthing = true,
  services_other = 'Antenatal Education/Birth Preparation',
  avail_weekdays_evenings = true,
  avail_weekends_mornings = true,
  avail_weekends_afternoons = true,
  avail_weekends_evenings = true,
  supports_solo_parents = true,
  supports_families_of_colour = true,
  supports_neurodivergent = true,
  supports_trauma_survivors = true,
  supports_bereavement = true,
  supports_complex_health = true,
  supports_home_births = true,
  supports_water_births = true,
  supports_caesareans = true,
  care_antenatal_planning = true,
  care_birth_support = true,
  care_postnatal_support = true,
  care_style = 'Emotionally attuned',
  hourly_rate = 60,
  gdpr_consent = true,
  insurance_certificate_expires = '2026-03-08',
  typeform_response_id = 'b41kp5q294ocwpcb410n8ywpzt2xz35p',
  intake_completed_at = '2026-01-23 17:12:52'
WHERE email = 'calmparentscalmbirth@outlook.com'